name: Release

on:
  push:
    tags:
      - 'v*'

permissions:
  contents: write

jobs:
  goreleaser:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
        with:
          # Allow goreleaser to access older tag information.
          fetch-depth: 0

      - uses: actions/setup-go@v6
        with:
          go-version-file: .go-version

      - uses: hashicorp/setup-terraform@v3
        id: setup-terraform
        with:
          terraform_wrapper: false

      - uses: cloudamqp/lavinmq-action@main

      - name: Run tests against LavinMQ
        run: go test ./lavinmq/ -v
        env:
          TF_ACC: 1
          TF_ACC_TERRAFORM_PATH: ${{ steps.setup-terraform.outputs.terraform_path }}
          LAVINMQ_PASSTHROUGH: 1
          LAVINMQ_API_BASEURL: http://localhost:15672/
          LAVINMQ_API_USERNAME: guest
          LAVINMQ_API_PASSWORD: guest
          TEST_AMQP_URI: "amqp://guest@//"

      - name: Import GPG key
        uses: crazy-max/ghaction-import-gpg@e89d40939c28e39f97cf32126055eeae86ba74ec # v6.3.0
        id: import_gpg
        with:
          gpg_private_key: ${{ secrets.GPG_PRIVATE_KEY }}
          passphrase: ${{ secrets.PASSPHRASE }}

      - name: Run GoReleaser
        uses: goreleaser/goreleaser-action@ec59f474b9834571250b370d4735c50f8e2d1e29 # v7.0.0
        with:
          version: ~> v2
          args: release --clean
        env:
          GPG_FINGERPRINT: ${{ steps.import_gpg.outputs.fingerprint }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
